-- =========================================================
-- CAFETERIA MENUS 4-WEEK CYCLE SCHEMA & SEED
-- =========================================================

create table if not exists public.cafeteria_menus (
  id text primary key,
  week_number integer not null check (week_number between 1 and 4),
  day_of_week text not null check (day_of_week in ('Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday')),
  date date,
  meal_type text not null check (meal_type in ('Breakfast', 'Brunch', 'Lunch', 'Dinner', 'Soup', 'Grill Station')),
  station text not null check (station in ('Main Dining', 'Grill Station', 'Soup Station', 'Breakfast Bar')),
  items jsonb not null default '[]'::jsonb,
  updated_at timestamptz default now()
);

alter table public.cafeteria_menus enable row level security;

drop policy if exists "cafeteria_menus: public read" on public.cafeteria_menus;
create policy "cafeteria_menus: public read"
  on public.cafeteria_menus for select
  using (true);

drop policy if exists "cafeteria_menus: admin write" on public.cafeteria_menus;
create policy "cafeteria_menus: admin write"
  on public.cafeteria_menus for all
  using (
    exists (
      select 1 from public.students
      where students.id = auth.uid()
      and students.role in ('admin', 'cafeteria_admin')
    )
  );

create index if not exists idx_cafeteria_menus_week_day on public.cafeteria_menus(week_number, day_of_week);
create index if not exists idx_cafeteria_menus_meal_type on public.cafeteria_menus(meal_type);

insert into public.cafeteria_menus (id, week_number, day_of_week, date, meal_type, station, items, updated_at) values
('w1-thu-breakfast', 1, 'Thursday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w1-thu-lunch', 1, 'Thursday', null, 'Lunch', 'Main Dining', '["Fresh Grilled Glazed Ginger Chicken","Veggie Stir Fry","Shrimp Fried Rice","Steamed Rice","California Blend","Steamed Broccoli","Veggie Egg Rolls","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w1-thu-dinner', 1, 'Thursday', null, 'Dinner', 'Main Dining', '["Garlic Parmesan Chicken","Pasta Shells"]'::jsonb, now()),
('w1-thu-soup', 1, 'Thursday', null, 'Soup', 'Soup Station', '["Creamy Potato Vegetarian Soup"]'::jsonb, now()),
('w1-thu-grill', 1, 'Thursday', null, 'Grill Station', 'Grill Station', '["Florentine","Smoke Sausage w/ Onions & Peppers","Dirty Rice","Sauteed Kale","Capri Vegetable Medley","Dinner Rolls","Cornbread","Burgers","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w1-fri-breakfast', 1, 'Friday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w1-fri-lunch', 1, 'Friday', null, 'Lunch', 'Main Dining', '["Fried Catfish / Grilled Tilapia","Pasta Primavera","Cajun Rotisserie Chicken","Yellow Macaroni & Cheese","Black-Eye Peas","Collard Greens","Candied Yams","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w1-fri-dinner', 1, 'Friday', null, 'Dinner', 'Main Dining', '["Honey BBQ Ribs","Veggie Stir Fry","BBQ Cornbread"]'::jsonb, now()),
('w1-fri-soup', 1, 'Friday', null, 'Soup', 'Soup Station', '["Gumbo"]'::jsonb, now()),
('w1-fri-grill', 1, 'Friday', null, 'Grill Station', 'Grill Station', '["Rotisserie Chicken","Yellow Rice","Cabbage","Fresh Vegetable Medley","Buttered Rolls","Chicken Philly","Turkey Sliders w/ Caramelized Onions","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w1-sat-brunch', 1, 'Saturday', null, 'Brunch', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w1-sat-lunch', 1, 'Saturday', null, 'Lunch', 'Main Dining', '["Chicken Tenders","Vegan Meatless Paella","Rolls","Cornbread"]'::jsonb, now()),
('w1-sat-dinner', 1, 'Saturday', null, 'Dinner', 'Main Dining', '["Wing Bar","Stuffed Squash","Baked Lemon Pepper Fish","Oven Roasted Red Skin Potatoes","Corn on the Cob","Baked Beans","Buttered Rolls"]'::jsonb, now()),
('w1-sat-grill', 1, 'Saturday', null, 'Grill Station', 'Grill Station', '["Chili Dog","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w1-sun-brunch', 1, 'Sunday', null, 'Brunch', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w1-sun-lunch', 1, 'Sunday', null, 'Lunch', 'Main Dining', '["Rosemary Garlic Rotisserie Chicken","Grilled Potato & Spinach Burritos","Steamed Rice","Broccoli Spears w/ Cheese","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w1-sun-dinner', 1, 'Sunday', null, 'Dinner', 'Main Dining', '["Carving Tom Turkey w/ Cornbread Dressing","Portobello Stuffed w/ Corn & Roasted Tomatoes","Rosemary Garlic Rotisserie Chicken","Yellow Macaroni & Cheese","Collard Greens","Candied Yams","Buttered Rolls","Cornbread"]'::jsonb, now()),
('w1-sun-grill', 1, 'Sunday', null, 'Grill Station', 'Grill Station', '["Chicken Po Boy","French Fries","Cheese Pizza","Ham & Pineapple Pizza"]'::jsonb, now()),
('w1-mon-breakfast', 1, 'Monday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w1-mon-lunch', 1, 'Monday', null, 'Lunch', 'Main Dining', '["Fried Chicken","Tempura Fried Zucchini","Cajun Baked Fish w/ Spinach","Rice Pilaf","Pinto Beans","California Blend","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w1-mon-dinner', 1, 'Monday', null, 'Dinner', 'Main Dining', '["Chicken Parmesan","Rasta Pasta","Herb Crusted Fish","Steamed Rice","Cabbage","Capri Vegetable Medley","Buttered Rolls","Cornbread"]'::jsonb, now()),
('w1-mon-soup', 1, 'Monday', null, 'Soup', 'Soup Station', '["Chicken Tortilla Soup"]'::jsonb, now()),
('w1-mon-grill', 1, 'Monday', null, 'Grill Station', 'Grill Station', '["Classic Corn Dogs","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w1-tue-breakfast', 1, 'Tuesday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w1-tue-lunch', 1, 'Tuesday', null, 'Lunch', 'Main Dining', '["Chicken / Beef / Shrimp Tacos","Mexican Vegan Enchiladas","Lemon Pepper Rotisserie Chicken","Spanish Rice","Black Beans & Corn","Mexican Baked Beans","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w1-tue-dinner', 1, 'Tuesday', null, 'Dinner', 'Main Dining', '["Lemon Pepper Salmon","Ziti w/ Roasted Veggies","Lemon Pepper Rotisserie Chicken","Garlic Smashed Potatoes","Normandy Cut Vegetable Blend","Green Peas","Buttered Rolls","Cornbread"]'::jsonb, now()),
('w1-tue-soup', 1, 'Tuesday', null, 'Soup', 'Soup Station', '["Broccoli & Cheese Soup"]'::jsonb, now()),
('w1-tue-grill', 1, 'Tuesday', null, 'Grill Station', 'Grill Station', '["Spicy Chicken Sandwich","French Fries","Cheese Pizza","Beef Topping Pizza"]'::jsonb, now()),
('w1-wed-breakfast', 1, 'Wednesday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w1-wed-lunch', 1, 'Wednesday', null, 'Lunch', 'Main Dining', '["Fried Chicken","Vegan Lasagna","Cajun Baked Fish","Rotisserie Chicken Honey BBQ","Yellow Macaroni & Cheese","Candied Yams","Mixed Greens","Buttered Rolls","Cornbread"]'::jsonb, now()),
('w1-wed-dinner', 1, 'Wednesday', null, 'Dinner', 'Main Dining', '["Chicken Alfredo","Penne Pasta w/ Vegetables","Blackened Fish","Roasted Red Potatoes","Mixed Vegetables","Sauteed Cabbage","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w1-wed-soup', 1, 'Wednesday', null, 'Soup', 'Soup Station', '["Cuban Black Bean Soup"]'::jsonb, now()),
('w1-wed-grill', 1, 'Wednesday', null, 'Grill Station', 'Grill Station', '["Chicken Sausage Philly","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w2-thu-breakfast', 2, 'Thursday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w2-thu-lunch', 2, 'Thursday', null, 'Lunch', 'Main Dining', '["Sweet & Sour Pork","Veggie Stir Fry","Rotisserie Chicken","Steamed Rice","Steamed Broccoli","Veggie Egg Roll","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w2-thu-dinner', 2, 'Thursday', null, 'Dinner', 'Main Dining', '["BBQ Slice Beef Brisket","Pasta Shells Florentine","Rotisserie Chicken","Mashed Potatoes / Gravy","Creamed Spinach","Capri Vegetable Medley","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w2-thu-soup', 2, 'Thursday', null, 'Soup', 'Soup Station', '["Santa Fe - Turkey Chili"]'::jsonb, now()),
('w2-thu-grill', 2, 'Thursday', null, 'Grill Station', 'Grill Station', '["Hot Dog","Shrimp Po Boy","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w2-fri-breakfast', 2, 'Friday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w2-fri-lunch', 2, 'Friday', null, 'Lunch', 'Main Dining', '["Fried Catfish / Grilled Tilapia","Sweet & Sour Vegan Tenders","Cajun Rotisserie Chicken","Yellow Macaroni & Cheese","Collard Greens","Candied Yams","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w2-fri-dinner', 2, 'Friday', null, 'Dinner', 'Main Dining', '["Cheese Manicotti","Wing Bar","Cajun Shrimp","Cornbread"]'::jsonb, now()),
('w2-fri-soup', 2, 'Friday', null, 'Soup', 'Soup Station', '["Corn Chowder"]'::jsonb, now()),
('w2-fri-grill', 2, 'Friday', null, 'Grill Station', 'Grill Station', '["Pasta","Oven Roasted Potatoes","Whole Kernel Corn","Fresh Vegetable Medley","Buttered Rolls","Chicken Tender Basket","Bacon Cheese Burger","French Fries","Cheese Pizza","Beef Topping Pizza"]'::jsonb, now()),
('w2-sat-brunch', 2, 'Saturday', null, 'Brunch', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w2-sat-lunch', 2, 'Saturday', null, 'Lunch', 'Main Dining', '["Country Fried Steak w/ Gravy","Rotisserie Chicken","Garlic Mashed Potato","Green Bean Almandine","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w2-sat-dinner', 2, 'Saturday', null, 'Dinner', 'Main Dining', '["Grilled Cajun Tilapia","Stuffed Portabello","Rotisserie Chicken","Steamed Rice","Pinto Beans","Turnip Greens","Buttered Rolls","Cornbread"]'::jsonb, now()),
('w2-sat-grill', 2, 'Saturday', null, 'Grill Station', 'Grill Station', '["Buffalo Chicken Sandwich","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w2-sun-brunch', 2, 'Sunday', null, 'Brunch', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w2-sun-lunch', 2, 'Sunday', null, 'Lunch', 'Main Dining', '["Oven Roasted Potato & Spinach Taco","Rosemary Garlic Chicken Wings","Broccoli Spears w/ Cheese","Corn on the Cob","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w2-sun-dinner', 2, 'Sunday', null, 'Dinner', 'Main Dining', '["Fried Chicken","Breaded Ravioli","Rosemary Garlic Rotisserie Chicken","Yellow Macaroni & Cheese","Collard Greens","Candied Yams","Buttered Rolls","Cornbread"]'::jsonb, now()),
('w2-sun-grill', 2, 'Sunday', null, 'Grill Station', 'Grill Station', '["Beef Philly Cheesesteak","French Fries","Cheese Pizza","Ham & Pineapple Pizza"]'::jsonb, now()),
('w2-mon-breakfast', 2, 'Monday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w2-mon-lunch', 2, 'Monday', null, 'Lunch', 'Main Dining', '["Beef & Broccoli","Tempura Fried Zucchini","Chipotle Rotisserie Chicken","Mashed Potatoes","Green Beans","California Blend","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w2-mon-dinner', 2, 'Monday', null, 'Dinner', 'Main Dining', '["Jerk Beef Tips","Rasta Pasta","Jerk Spiced Cornbread"]'::jsonb, now()),
('w2-mon-soup', 2, 'Monday', null, 'Soup', 'Soup Station', '["Chicken Noodle Soup"]'::jsonb, now()),
('w2-mon-grill', 2, 'Monday', null, 'Grill Station', 'Grill Station', '["Rotisserie Chicken","Fried Rice","Sauteed Cabbage","Plantains","Buttered Rolls","Fish Sandwich","Chicken Quesadilla","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w2-tue-breakfast', 2, 'Tuesday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w2-tue-lunch', 2, 'Tuesday', null, 'Lunch', 'Main Dining', '["Chicken / Beef / Shrimp Tacos","Mexican Vegan Enchiladas","Lemon Pepper Rotisserie Chicken","Spanish Rice","Black Beans & Corn","Mexican Baked Beans & Corn","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w2-tue-dinner', 2, 'Tuesday', null, 'Dinner', 'Main Dining', '["Grilled Pork Chops","Whole Wheat Ziti w/ Roasted Veggies","Lemon Pepper Rotisserie Chicken"]'::jsonb, now()),
('w2-tue-soup', 2, 'Tuesday', null, 'Soup', 'Soup Station', '["Chicken Tortilla Soup"]'::jsonb, now()),
('w2-tue-grill', 2, 'Tuesday', null, 'Grill Station', 'Grill Station', '["Chicken","Garlic Smashed Potatoes","Normandy Cut Vegetable Blend","Green Beans Almandine","Buttered Rolls","Philly Cheese Steak","Meatball Sub","French Fries","Cheese Pizza","Beef Topping Pizza"]'::jsonb, now()),
('w2-wed-breakfast', 2, 'Wednesday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w2-wed-lunch', 2, 'Wednesday', null, 'Lunch', 'Main Dining', '["Shrimp Lo Mein","Penne Pasta w/ Vegetables","Rotisserie Chicken Honey BBQ","Roasted Red Potatoes","Mixed Vegetables","Sauteed Spinach","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w2-wed-dinner', 2, 'Wednesday', null, 'Dinner', 'Main Dining', '["Fried Chicken","Vegan Lasagna","Cajun Baked Fish","Rotisserie Chicken Honey BBQ","Yellow Macaroni & Cheese","Candied Yams","Mixed Greens","Buttered Rolls","Cornbread"]'::jsonb, now()),
('w2-wed-soup', 2, 'Wednesday', null, 'Soup', 'Soup Station', '["Beef & Noodle Soup"]'::jsonb, now()),
('w2-wed-grill', 2, 'Wednesday', null, 'Grill Station', 'Grill Station', '["Cheese Burger","Chicken Po Boy","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w3-thu-breakfast', 3, 'Thursday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w3-thu-lunch', 3, 'Thursday', null, 'Lunch', 'Main Dining', '["Cajun Baked Fish","Stuffed Shells","Beef & Noodle Casserole","Rotisserie Chicken","Yellow Rice","Green Beans","California Blend","Rolls","Cornbread"]'::jsonb, now()),
('w3-thu-dinner', 3, 'Thursday', null, 'Dinner', 'Main Dining', '["Shrimp Lo Mein","Veggie Egg Rolls","Sausage w/ Onions & Peppers","BBQ Rotisserie Chicken","Rice Pilaf","Mixed Vegetables","Steamed Broccoli","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w3-thu-soup', 3, 'Thursday', null, 'Soup', 'Soup Station', '["Santa Fe - Turkey Chili"]'::jsonb, now()),
('w3-thu-grill', 3, 'Thursday', null, 'Grill Station', 'Grill Station', '["Burger","Buffalo Cauliflower Bites","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w3-fri-breakfast', 3, 'Friday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w3-fri-lunch', 3, 'Friday', null, 'Lunch', 'Main Dining', '["Southern Fried Fish","Baked Fish","BBQ Rotisserie Chicken Honey Garlic","Yellow Macaroni & Cheese","Collard Greens","Candied Yams","Yellow Squash & Onions","Rolls","Cornbread"]'::jsonb, now()),
('w3-fri-dinner', 3, 'Friday', null, 'Dinner', 'Main Dining', '["Wing Bar (Lemon Pepper / Buffalo)","Veggie Tenders","Grilled Tilapia w/ Cajun Sauce","Baked Potatoes","Corn on the Cob","Sauteed Asparagus","Dinner Rolls","Corn Bread"]'::jsonb, now()),
('w3-fri-soup', 3, 'Friday', null, 'Soup', 'Soup Station', '["Corn Chowder"]'::jsonb, now()),
('w3-fri-grill', 3, 'Friday', null, 'Grill Station', 'Grill Station', '["Boneless Wings","Turkey Burger w/ Cheese","French Fries","Cheese Pizza","Beef Topping Pizza"]'::jsonb, now()),
('w3-sat-brunch', 3, 'Saturday', null, 'Brunch', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w3-sat-lunch', 3, 'Saturday', null, 'Lunch', 'Main Dining', '["Carving Roast Turkey w/ Cornbread Dressing","Vegetarian Lasagna","Rotisserie Chicken","Rice Pilaf","Spinach Casserole","Brussel Sprouts w/ Caramelized Onions","Rolls","Cornbread"]'::jsonb, now()),
('w3-sat-dinner', 3, 'Saturday', null, 'Dinner', 'Main Dining', '["Wing Bar (Lemon Pepper / Buffalo)","Veggie Tenders","Grilled Tilapia w/ Cajun Sauce","Baked Potatoes","Corn on the Cob","Sauteed Asparagus","Dinner Rolls","Corn Bread"]'::jsonb, now()),
('w3-sat-grill', 3, 'Saturday', null, 'Grill Station', 'Grill Station', '["Burger","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w3-sun-brunch', 3, 'Sunday', null, 'Brunch', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w3-sun-lunch', 3, 'Sunday', null, 'Lunch', 'Main Dining', '["Carving Station (Ham)","Fried Chicken","Vegetable Lasagna","Rosemary Garlic Rotisserie Chicken","Macaroni & Cheese","Fried Cabbage with Julienne Carrots & Onions","Candied Yams","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w3-sun-dinner', 3, 'Sunday', null, 'Dinner', 'Main Dining', '["Carving Station (Pork Loin)","Penne Pasta w/ Vegetables","Rosemary Garlic Rotisserie Chicken","Twice Baked Potato","Sauteed Green Beans","Succotash","Rolls","Cornbread"]'::jsonb, now()),
('w3-sun-grill', 3, 'Sunday', null, 'Grill Station', 'Grill Station', '["Chili Dog","French Fries","Cheese Pizza","Ham & Pineapple Pizza"]'::jsonb, now()),
('w3-mon-breakfast', 3, 'Monday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w3-mon-lunch', 3, 'Monday', null, 'Lunch', 'Main Dining', '["BBQ Ribs","Grilled Vegetables w/ Meatless Beef Stir Fry","Shrimp Jambalaya","Chipotle Rotisserie Chicken","Scalloped Potato","California Blend","Navy Beans","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w3-mon-dinner', 3, 'Monday', null, 'Dinner', 'Main Dining', '["Blackened Fish w/ Roasted Peppers","Eggplant Parmesan","Fried Pork Chop","Shrimp Fried Rice","Parslied Red Potatoes","Seasoned Green Beans","Peas & Carrots","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w3-mon-soup', 3, 'Monday', null, 'Soup', 'Soup Station', '["Chicken Tortilla Soup"]'::jsonb, now()),
('w3-mon-grill', 3, 'Monday', null, 'Grill Station', 'Grill Station', '["BBQ Chicken Sandwich","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w3-tue-breakfast', 3, 'Tuesday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w3-tue-lunch', 3, 'Tuesday', null, 'Lunch', 'Main Dining', '["Shrimp Fajitas Tacos","Meatless Chicken Fajitas","Chicken Fajitas","Lemon Pepper Rotisserie Chicken","Spanish Rice","Fire Roasted Corn & Black Beans","Pinto Beans","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w3-tue-dinner', 3, 'Tuesday', null, 'Dinner', 'Main Dining', '["Fried Okra","Shrimp Alfredo","Country Fried Steak","Black Bean & Rice","Lemon Pepper Rotisserie Chicken"]'::jsonb, now()),
('w3-tue-soup', 3, 'Tuesday', null, 'Soup', 'Soup Station', '["Broccoli & Cheese Soup"]'::jsonb, now()),
('w3-tue-grill', 3, 'Tuesday', null, 'Grill Station', 'Grill Station', '["Loaded Garlic Smashed Potatoes","Mixed Veggies","Boneless Chicken Wings","Shrimp Po Boy","French Fries","Cheese Pizza","Beef Topping Pizza"]'::jsonb, now()),
('w3-wed-breakfast', 3, 'Wednesday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w3-wed-lunch', 3, 'Wednesday', null, 'Lunch', 'Main Dining', '["Teriyaki Chicken w/ Grilled Pineapple","Chinese Pepper Steak & Broccoli","Angel Hair Pasta w/ Fresh Veggies","Rotisserie Chicken","Yellow Rice","Smothered Cabbage","Broccoli & Cheese","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w3-wed-dinner', 3, 'Wednesday', null, 'Dinner', 'Main Dining', '["Spaghetti Bolognese","Fried Chicken","Vegan Jambalaya","Rotisserie Chicken","Cheddar Macaroni & Cheese","Collard Greens","Candied Yams","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w3-wed-soup', 3, 'Wednesday', null, 'Soup', 'Soup Station', '["Chicken & Noodle Soup"]'::jsonb, now()),
('w3-wed-grill', 3, 'Wednesday', null, 'Grill Station', 'Grill Station', '["Chicken Po Boy","Chili Dog","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w4-thu-breakfast', 4, 'Thursday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w4-thu-lunch', 4, 'Thursday', null, 'Lunch', 'Main Dining', '["Smoked Sausage w/ Peppers & Onions","Greek Stuffed Zucchini Squash","Rotisserie Chicken Cajun Spice","Mashed Potatoes","Corn on the Cob","California Blend","Rolls","Cornbread"]'::jsonb, now()),
('w4-thu-dinner', 4, 'Thursday', null, 'Dinner', 'Main Dining', '["Chicken Fried Tofu","Grilled Tilapia w/ Mango Salsa","Rotisserie Chicken Cajun Spice","Yellow Rice","Seasoned Lima Beans","Fresh Vegetable Medley","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w4-thu-soup', 4, 'Thursday', null, 'Soup', 'Soup Station', '["Potato and Corn Chowder"]'::jsonb, now()),
('w4-thu-grill', 4, 'Thursday', null, 'Grill Station', 'Grill Station', '["Grilled Hot Dog","Bacon Cheese Burger","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w4-fri-breakfast', 4, 'Friday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w4-fri-lunch', 4, 'Friday', null, 'Lunch', 'Main Dining', '["Southern Fried Fish","Stuffed Squash","Baked Fish","BBQ Rotisserie Chicken Honey Garlic","Yellow Macaroni & Cheese","Collard Greens","Candied Yams","Yellow Squash","Rolls","Cornbread"]'::jsonb, now()),
('w4-fri-dinner', 4, 'Friday', null, 'Dinner', 'Main Dining', '["Chicken Wing Bar","Garlic & Red Pepper Penne","Cornbread"]'::jsonb, now()),
('w4-fri-soup', 4, 'Friday', null, 'Soup', 'Soup Station', '["Chicken and Rice Soup"]'::jsonb, now()),
('w4-fri-grill', 4, 'Friday', null, 'Grill Station', 'Grill Station', '["Cajun Shrimp Pasta","Oven Roasted Baby Reds","Baked Beans","Whole Green Beans","Rolls","Chicken Philly","French Fries","Cheese Pizza","Beef Topping Pizza"]'::jsonb, now()),
('w4-sat-brunch', 4, 'Saturday', null, 'Brunch', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w4-sat-lunch', 4, 'Saturday', null, 'Lunch', 'Main Dining', '["Grilled Chicken Breast","Vegan Beef Stir Fry","Beef Tips over Rice","Steamed Rice","Fresh Fried Pork Chops","Portobella Stuffed w/ Corn & Roasted Tomatoes","Rotisserie Chicken Italian Herb","Sauteed Spinach","Squash Casserole","Candied Yams","Rolls","Cornbread"]'::jsonb, now()),
('w4-sat-soup', 4, 'Saturday', null, 'Soup', 'Soup Station', '["Vegetarian Cream of Broccoli"]'::jsonb, now()),
('w4-sat-grill', 4, 'Saturday', null, 'Grill Station', 'Grill Station', '["BBQ Beef Sliders","Grilled Chicken Sandwich","Veggie Blend","Broccoli Spears w/ Cheese","Dinner Rolls","Cornbread","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w4-sun-brunch', 4, 'Sunday', null, 'Brunch', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w4-sun-lunch', 4, 'Sunday', null, 'Lunch', 'Main Dining', '["Carving Station (Maple Glazed Ham)","Vegetarian Lasagna","Rotisserie Chicken","Braised Cabbage","Cajun Rice","Pinto Beans","Rolls","Cornbread"]'::jsonb, now()),
('w4-sun-dinner', 4, 'Sunday', null, 'Dinner', 'Main Dining', '["Fried Chicken","Veggie Tenders","Rosemary Garlic Rotisserie Chicken","Yellow Macaroni & Cheese","Collard Greens","Candied Yams","Buttered Rolls"]'::jsonb, now()),
('w4-sun-soup', 4, 'Sunday', null, 'Soup', 'Soup Station', '["Vegan Garden Vegetable Soup"]'::jsonb, now()),
('w4-sun-grill', 4, 'Sunday', null, 'Grill Station', 'Grill Station', '["Burger","Beef Philly Cheesesteak","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w4-mon-breakfast', 4, 'Monday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w4-mon-lunch', 4, 'Monday', null, 'Lunch', 'Main Dining', '["Country Fried Steak","Stuffed Pepper","Rotisserie Chicken Portuguese","Au Gratin Potatoes","Broccoli & Cheese","Sauteed Spinach","Rolls","Cornbread"]'::jsonb, now()),
('w4-mon-dinner', 4, 'Monday', null, 'Dinner', 'Main Dining', '["Blackened Fish w/ Roasted Peppers","Cheese Manicotti","BBQ Ribs","Mashed Potatoes","Sauteed Spinach","Veggie Blend","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w4-mon-soup', 4, 'Monday', null, 'Soup', 'Soup Station', '["Prize Winning Chili"]'::jsonb, now()),
('w4-mon-grill', 4, 'Monday', null, 'Grill Station', 'Grill Station', '["Fried Fish Sandwich","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now()),
('w4-tue-breakfast', 4, 'Tuesday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w4-tue-lunch', 4, 'Tuesday', null, 'Lunch', 'Main Dining', '["Turkey Tacos","Chicken / Shrimp Tacos","Spinach & Cheese Quesadilla","Rotisserie Chicken Garlic Citrus","Spanish Rice","Mexican Corn","Black Beans","Rolls","Cornbread"]'::jsonb, now()),
('w4-tue-dinner', 4, 'Tuesday', null, 'Dinner', 'Main Dining', '["Lemon Pepper Wings","Baked Meatless Ziti","Cornbread"]'::jsonb, now()),
('w4-tue-soup', 4, 'Tuesday', null, 'Soup', 'Soup Station', '["Tomato Bacon Soup"]'::jsonb, now()),
('w4-tue-grill', 4, 'Tuesday', null, 'Grill Station', 'Grill Station', '["Shrimp Alfredo","Rice & Gravy","Twice Bake Potatoes","Baked Beans","Dinner Rolls","Loaded Baked Potato Wedges","Sweet Chili Chicken Sandwich","French Fries","Cheese Pizza","Beef Topping Pizza"]'::jsonb, now()),
('w4-wed-breakfast', 4, 'Wednesday', null, 'Breakfast', 'Breakfast Bar', '["Grits","Omelet Station","Scrambled Eggs","Potatoes","Bacon","Chicken Sausage Patty","Vegetarian Sausage","Hot Butter Biscuits","Buttermilk Pancakes","Oatmeal","Hard-Boiled Eggs","Granola","Fruit"]'::jsonb, now()),
('w4-wed-lunch', 4, 'Wednesday', null, 'Lunch', 'Main Dining', '["Chinese Pepper Steaks","Veggie Egg Rolls","Chinese Chicken","Rice Pilaf","Glazed Baby Whole Carrots","Steamed Cabbage","Rolls","Cornbread"]'::jsonb, now()),
('w4-wed-dinner', 4, 'Wednesday', null, 'Dinner', 'Main Dining', '["Spaghetti Bolognese","Fried Chicken","Vegan Jambalaya","Rotisserie Chicken","Cheddar Macaroni & Cheese","Collard Greens","Candied Yams","Dinner Rolls","Cornbread"]'::jsonb, now()),
('w4-wed-soup', 4, 'Wednesday', null, 'Soup', 'Soup Station', '["Chicken Gumbo"]'::jsonb, now()),
('w4-wed-grill', 4, 'Wednesday', null, 'Grill Station', 'Grill Station', '["Grilled Chicken Tenders","French Fries","Cheese Pizza","Pepperoni Pizza"]'::jsonb, now())
on conflict (id) do update set
  week_number = excluded.week_number,
  day_of_week = excluded.day_of_week,
  meal_type = excluded.meal_type,
  station = excluded.station,
  items = excluded.items,
  updated_at = now();
